Repository team-yello/YELLO-Android, pull requests merged in 2023-07, with the labels that each got.

#9 [CHORE] Auth Interceptor 추가
  app/build.gradle.kts
  app/src/debug/java/com/yello/FlipperSetUp.kt
  app/src/main/java/com/yello/MyApp.kt
  app/src/main/java/com/yello/di/AppModule.kt
  app/src/main/java/com/yello/di/RetrofitModule.kt
  app/src/main/java/com/yello/di/SharedPrefModule.kt
  app/src/main/java/com/yello/di/qualifier/InterceptorQualifier.kt
  app/src/main/java/com/yello/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core-ui/build.gradle.kts
  core-ui/src/androidTest/java/com/example/ui/ExampleInstrumentedTest.kt
  core-ui/src/main/AndroidManifest.xml
  core-ui/src/main/java/com/example/ui/base/BindingActivity.kt
  core-ui/src/main/java/com/example/ui/base/BindingDialogFragment.kt
  core-ui/src/main/java/com/example/ui/base/BindingFragment.kt
  core-ui/src/main/java/com/example/ui/context/ContextExt.kt
  core-ui/src/main/java/com/example/ui/fragment/FragmentExt.kt
  core-ui/src/main/java/com/example/ui/intent/ExtraExt.kt
  core-ui/src/main/java/com/example/ui/view/ViewExt.kt
  core-ui/src/test/java/com/example/ui/ExampleUnitTest.kt
  data/build.gradle.kts
  data/src/androidTest/java/com/example/data/ExampleInstrumentedTest.kt
  data/src/main/java/com/example/data/local/YelloDataStoreImpl.kt
  data/src/main/java/com/example/data/model/response/auth/ResponseAuthToken.kt
  data/src/main/java/com/example/data/remote/interceptor/AuthInterceptor.kt
  data/src/main/java/com/example/data/util/FileParser.kt
  data/src/test/java/com/example/data/ExampleUnitTest.kt
  domain/build.gradle.kts
  domain/src/main/java/com/example/domain/YelloDataStore.kt
Labels: CHORE 🎀, 채연 🐸

#16 [CHORE/#10] color 및 typography 설정
  app/src/main/res/font/font_pretendard_bold.xml
  app/src/main/res/font/font_pretendard_medium.xml
  app/src/main/res/font/font_pretendard_regular.xml
  app/src/main/res/font/font_pretendard_semibold.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/font/unbounded_black.ttf
  app/src/main/res/font/unbounded_bold.ttf
  app/src/main/res/font/unbounded_extrabold.ttf
  app/src/main/res/font/unbounded_extralight.ttf
  app/src/main/res/font/unbounded_light.ttf
  app/src/main/res/font/unbounded_medium.ttf
  app/src/main/res/font/unbounded_regular.ttf
  app/src/main/res/font/unbounded_semibold.ttf
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: CHORE 🎀, PULL REQUEST 🚀, 채연 🐸

#14 [UI/#11] Onboarding / viewpager
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yello/presentation/onboarding/Activity/OnBoardingActivity.kt
  app/src/main/java/com/yello/presentation/onboarding/ViewPagerFragmentAdapter.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/AddFriendFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/CodeFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/GenderFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/NameIdFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/SchoolFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/StartAppFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/StudentIdFragment.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_addfreind.xml
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_gender.xml
  app/src/main/res/layout/fragment_name_id.xml
  app/src/main/res/layout/fragment_school.xml
  app/src/main/res/layout/fragment_startapp.xml
  app/src/main/res/layout/fragment_studentid.xml
Labels: PULL REQUEST 🚀, UI 💐, 민주 🌳

#17 [UI/#15] Main / BottomNavigationView 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yello/presentation/MainActivity.kt
  app/src/main/java/com/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/res/drawable/ic_main_look_selected.xml
  app/src/main/res/drawable/ic_main_look_unselected.xml
  app/src/main/res/drawable/ic_main_my_yello_selected.xml
  app/src/main/res/drawable/ic_main_my_yello_unselected.xml
  app/src/main/res/drawable/ic_main_profile_selected.xml
  app/src/main/res/drawable/ic_main_profile_unselected.xml
  app/src/main/res/drawable/ic_main_recommend_selected.xml
  app/src/main/res/drawable/ic_main_recommend_unselected.xml
  app/src/main/res/drawable/ic_main_yello_selected.xml
  app/src/main/res/drawable/ic_main_yello_unselected.xml
  app/src/main/res/drawable/sel_main_color_bnv_label.xml
  app/src/main/res/drawable/sel_main_icon_bnv_look.xml
  app/src/main/res/drawable/sel_main_icon_bnv_my_yello.xml
  app/src/main/res/drawable/sel_main_icon_bnv_profile.xml
  app/src/main/res/drawable/sel_main_icon_bnv_recommend.xml
  app/src/main/res/drawable/sel_main_icon_bnv_yello.xml
  app/src/main/res/drawable/shape_grayscales900_fill_top10_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/layout/fragment_my_yello.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/fragment_yello.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: PULL REQUEST 🚀, UI 💐, 채연 🐸

#21 [FEAT/#12] onBoarding 소셜 로그인 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yello/MyApp.kt
  app/src/main/java/com/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/shape_kakao_yellow_fill_8_rect.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_social_sync.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  settings.gradle.kts
Labels: FEAT ✨, 상호 🍀

#26 [FIX/#25] Main / bottom navigation view 간격 및 아이콘 설정
  app/src/main/java/com/yello/presentation/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_yello.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#27 [UI/#22] Recommend / UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendAdapter.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendKakaoFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendKakaoViewModel.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendSchoolFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendSchoolViewModel.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendViewHolder.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendViewPagerAdapter.kt
  app/src/main/res/anim/slide_out_right.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_exit.xml
  app/src/main/res/drawable/ic_kakao_share.xml
  app/src/main/res/drawable/ic_link_share.xml
  app/src/main/res/drawable/ic_recommend_btn_pressed.xml
  app/src/main/res/drawable/ic_right.xml
  app/src/main/res/drawable/img_banner_invite.xml
  app/src/main/res/drawable/sel_recommend_ic_list_btn.xml
  app/src/main/res/drawable/shape_rect.xml
  app/src/main/res/drawable/shape_unselected_tab_indicator.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/fragment_recommend_invite_dialog.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_recommend_school.xml
  app/src/main/res/layout/item_recommend_list.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  core-ui/src/main/java/com/example/ui/base/BindingDialogFragment.kt
  core-ui/src/main/java/com/example/ui/intent/ExtraExt.kt
  domain/src/main/java/com/example/domain/entity/RecommendModel.kt
Labels: UI 💐, 상호 🍀

#29 [FEAT] 내 옐로 리스트 구현
  app/src/main/java/com/yello/MyApp.kt
  app/src/main/java/com/yello/di/AppModule.kt
  app/src/main/java/com/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/yello/presentation/main/myyello/MyYelloAdapter.kt
  app/src/main/java/com/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/yello/presentation/util/BaseLinearRcvItemDeco.kt
  app/src/main/java/com/yello/presentation/util/ResolutionMetrics.kt
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_read_yello_point.xml
  app/src/main/res/drawable/ic_yello_blue.xml
  app/src/main/res/drawable/ic_yello_pink.xml
  app/src/main/res/drawable/shape_fill_yello500_8dp.xml
  app/src/main/res/layout/fragment_my_yello.xml
  app/src/main/res/layout/item_my_yello.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  data/src/main/assets/fake_total_yello.json
  data/src/main/java/com/example/data/model/response/yello/ResponseMyYello.kt
  domain/src/main/java/com/example/domain/entity/MyYello.kt
  domain/src/main/java/com/example/domain/enum/GenderEnum.kt
Labels: FEAT ✨, 강민 🦖

#30 [UI/#28] Profile / UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/ic_yello_launcher-playstore.png
  app/src/main/java/com/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileFragment.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileFriendAdpater.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileFriendDeleteBottomSheet.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileFriendItemBottomSheet.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileFriendViewHolder.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileManageActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileQuitActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileQuitDialog.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileQuitForSureActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendKakaoFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendKakaoViewModel.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendSchoolFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendViewHolder.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendViewPagerAdapter.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_arrow_upward.xml
  app/src/main/res/drawable/ic_yello_launcher_background.xml
  app/src/main/res/drawable/ic_yello_launcher_foreground.xml
  app/src/main/res/drawable/ic_yellow_plus.xml
  app/src/main/res/drawable/shape_black_fill_rect.xml
  app/src/main/res/drawable/shape_fab_circle.xml
  app/src/main/res/drawable/shape_grayscales700_line_8_rect.xml
  app/src/main/res/drawable/shape_grayscales800_fill_8_rect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_8_rect.xml
  app/src/main/res/layout/activity_profile_manage.xml
  app/src/main/res/layout/activity_profile_quit.xml
  app/src/main/res/layout/activity_profile_quit_for_sure.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_profile_friend_delete_bottom_sheet.xml
  app/src/main/res/layout/fragment_profile_friend_item_bottom_sheet.xml
  app/src/main/res/layout/fragment_profile_quit_dialog.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_recommend_school.xml
  app/src/main/res/layout/item_friends_list.xml
  app/src/main/res/mipmap-anydpi-v26/ic_yello_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_yello_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-hdpi/ic_yello_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-mdpi/ic_yello_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_yello_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_yello_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_yello_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  domain/src/main/java/com/example/domain/entity/ProfileFriendModel.kt
Labels: UI 💐, 상호 🍀

#34 [FIX/#33] ViewPager 페이지 전환 시 애니메이션 적용
  app/src/main/java/com/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/vote/VoteActivity.kt
  app/src/main/java/com/yello/presentation/util/ViewPagerExt.kt
  app/src/main/res/layout/fragment_my_yello.xml
  core-ui/src/main/java/com/example/ui/transformation/FadeOutTransformation.kt
Labels: FIX 🔨

#39 [FEAT/#32] OnBoarding / 토큰 교체 서버통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yello/di/DataSourceModule.kt
  app/src/main/java/com/yello/di/RepositoryModule.kt
  app/src/main/java/com/yello/di/ServiceModule.kt
  app/src/main/java/com/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/res/drawable/ic_alert.xml
  app/src/main/res/drawable/img_on_boarding_start.xml
  app/src/main/res/drawable/img_on_boarding_sync.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_social_sync.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/datasource/OnboardingDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/OnboardingDataSourceImpl.kt
  data/src/main/java/com/example/data/model/request/RequestTest.kt
  data/src/main/java/com/example/data/model/request/onboarding/RequestServiceTokenDto.kt
  data/src/main/java/com/example/data/model/response/onboarding/ResponseAuthToken.kt
  data/src/main/java/com/example/data/model/response/onboarding/ResponseServiceTokenDto.kt
  data/src/main/java/com/example/data/remote/interceptor/AuthInterceptor.kt
  data/src/main/java/com/example/data/remote/service/OnboardingService.kt
  data/src/main/java/com/example/data/repository/OnboardingRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/RequestServiceTokenModel.kt
  domain/src/main/java/com/example/domain/entity/ServiceTokenModel.kt
  domain/src/main/java/com/example/domain/repository/OnboardingRepository.kt
Labels: FEAT ✨, 상호 🍀

#40 [FIX/#32] OnBoarding / 토큰 교체 서버통신 수정
  app/src/main/java/com/yello/di/DataSourceModule.kt
  app/src/main/java/com/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileQuitForSureActivity.kt
Labels: FIX 🔨, 상호 🍀

#43 [ FEAT/#42] 내 쪽지 상세보기 로직 & Ui & 서버 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yello/di/DataSourceModule.kt
  app/src/main/java/com/yello/presentation/main/myyello/MyYelloAdapter.kt
  app/src/main/java/com/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
  app/src/main/java/com/yello/presentation/main/myyello/read/PointUseDialog.kt
  app/src/main/java/com/yello/util/Utils.kt
  app/src/main/java/com/yello/util/binding/BindingAdapter.kt
  app/src/main/res/drawable-hdpi/ic_instagram.png
  app/src/main/res/drawable-mdpi/ic_instagram.png
  app/src/main/res/drawable-xhdpi/ic_instagram.png
  app/src/main/res/drawable-xxhdpi/ic_instagram.png
  app/src/main/res/drawable-xxxhdpi/ic_instagram.png
  app/src/main/res/drawable/shape_fill_black_32dp.xml
  app/src/main/res/drawable/shape_fill_gray900_12dp.xml
  app/src/main/res/drawable/shape_white_35per_8dp.xml
  app/src/main/res/layout/activity_my_yello_read.xml
  app/src/main/res/layout/dialog_point_use.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Versions.kt
  data/src/main/assets/fake_detail_yello.json
  data/src/main/assets/fake_total_yello.json
  data/src/main/java/com/example/data/model/response/yello/ResponseMyYello.kt
  data/src/main/java/com/example/data/model/response/yello/ResponseYelloDetail.kt
  data/src/main/java/com/example/data/remote/service/YelloService.kt
  data/src/main/java/com/example/data/repository/YelloRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/MyYello.kt
  domain/src/main/java/com/example/domain/entity/YelloDetail.kt
  domain/src/main/java/com/example/domain/enum/PointEnum.kt
Labels: FEAT ✨, 강민 🦖

#44 [FEAT/#37] Yello / 옐로 서버통신 연결
  app/src/main/java/com/yello/MyApp.kt
  app/src/main/java/com/yello/di/DataSourceModule.kt
  app/src/main/java/com/yello/di/RepositoryModule.kt
  app/src/main/java/com/yello/di/ServiceModule.kt
  app/src/main/java/com/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
  app/src/main/java/com/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/yello/presentation/main/yello/lock/YelloLockFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/point/PointFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/vote/NoteState.kt
  app/src/main/java/com/yello/presentation/main/yello/vote/VoteActivity.kt
  app/src/main/java/com/yello/presentation/main/yello/vote/VoteState.kt
  app/src/main/java/com/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/yello/presentation/main/yello/vote/note/NoteFragment.kt
  app/src/main/java/com/yello/presentation/yello/YelloViewModel.kt
  app/src/main/java/com/yello/util/binding/BindingAdapter.kt
  app/src/main/res/layout/activity_vote.xml
  app/src/main/res/layout/fragment_note.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/layout/fragment_yello_start.xml
  app/src/main/res/layout/fragment_yello_wait.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/datasource/VoteDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/VoteDataSourceImpl.kt
  data/src/main/java/com/example/data/datasource/remote/YelloDataSourceImpl.kt
  data/src/main/java/com/example/data/model/request/RequestPostVoteDto.kt
  data/src/main/java/com/example/data/model/response/BaseResponse.kt
  data/src/main/java/com/example/data/model/response/vote/ResponseGetFriendShuffleDto.kt
  data/src/main/java/com/example/data/model/response/vote/ResponseGetVoteAvailableDto.kt
  data/src/main/java/com/example/data/model/response/vote/ResponseGetVoteQuestionDto.kt
  data/src/main/java/com/example/data/model/response/vote/ResponsePostVoteDto.kt
  data/src/main/java/com/example/data/remote/interceptor/AuthInterceptor.kt
  data/src/main/java/com/example/data/remote/service/VoteService.kt
  data/src/main/java/com/example/data/repository/VoteRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/YelloRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/CheckName.kt
  domain/src/main/java/com/example/domain/entity/RecommendModel.kt
  domain/src/main/java/com/example/domain/entity/type/ProgressType.kt
  domain/src/main/java/com/example/domain/entity/type/YelloState.kt
  domain/src/main/java/com/example/domain/entity/vote/Choice.kt
  domain/src/main/java/com/example/domain/entity/vote/ChoiceList.kt
  domain/src/main/java/com/example/domain/entity/vote/Note.kt
  domain/src/main/java/com/example/domain/entity/vote/VoteState.kt
  domain/src/main/java/com/example/domain/repository/VoteRepository.kt
  domain/src/main/java/com/example/domain/repository/YelloRepository.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 채연 🐸

#45 [FEAT/#41] Recommend / 서버 통신 구현
  app/src/main/ic_yello_launcher-playstore.png
  app/src/main/java/com/yello/di/DataSourceModule.kt
  app/src/main/java/com/yello/di/RepositoryModule.kt
  app/src/main/java/com/yello/di/ServiceModule.kt
  app/src/main/java/com/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/yello/presentation/main/profile/info/ProfileFriendViewHolder.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendAdapter.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendItemDecoration.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendKakaoFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendKakaoViewModel.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendSchoolFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendSchoolViewModel.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendViewHolder.kt
  app/src/main/res/drawable/ic_yello_launcher_foreground.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_recommend_school.xml
  app/src/main/res/layout/item_recommend_list.xml
  app/src/main/res/mipmap-hdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-hdpi/ic_yello_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-mdpi/ic_yello_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_yello_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_yello_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_yello_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_yello_launcher_round.png
  data/src/main/java/com/example/data/datasource/OnboardingDataSource.kt
  data/src/main/java/com/example/data/datasource/RecommendDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/OnboardingDataSourceImpl.kt
  data/src/main/java/com/example/data/datasource/remote/RecommendDataSourceImpl.kt
  data/src/main/java/com/example/data/model/request/recommend/RequestRecommendKakaoDto.kt
  data/src/main/java/com/example/data/model/response/onboarding/ResponseServiceTokenDto.kt
  data/src/main/java/com/example/data/model/response/recommend/ResponseRecommendAddDto.kt
  data/src/main/java/com/example/data/model/response/recommend/ResponseRecommendDto.kt
  data/src/main/java/com/example/data/remote/service/OnboardingService.kt
  data/src/main/java/com/example/data/remote/service/RecommendService.kt
  data/src/main/java/com/example/data/repository/OnboardingRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/RecommendRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/RecommendAddModel.kt
  domain/src/main/java/com/example/domain/entity/RecommendModel.kt
  domain/src/main/java/com/example/domain/entity/RequestRecommendKakaoModel.kt
  domain/src/main/java/com/example/domain/repository/OnboardingRepository.kt
  domain/src/main/java/com/example/domain/repository/RecommendRepository.kt
Labels: FEAT ✨, 상호 🍀

#56 [FEAT/#54] Onboarding / 친구추가 리스트 구현
  app/src/main/java/com/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/yello/presentation/main/yello/dialog/UnlockDialogFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/addfriend/AddFriendAdapter.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/res/layout/fragment_addfreind.xml
  data/src/main/java/com/example/data/datasource/OnboardingDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/OnboardingDataSourceImpl.kt
  data/src/main/java/com/example/data/model/request/onboarding/RequestOnboardingListDto.kt
  data/src/main/java/com/example/data/model/request/onboarding/RequestSignFriendDto.kt
  data/src/main/java/com/example/data/remote/interceptor/AuthInterceptor.kt
  data/src/main/java/com/example/data/remote/service/OnboardingService.kt
  data/src/main/java/com/example/data/repository/OnboardingRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/RequestOnboardingListModel.kt
  domain/src/main/java/com/example/domain/entity/onboarding/FriendGroup.kt
  domain/src/main/java/com/example/domain/entity/onboarding/FriendList.kt
  domain/src/main/java/com/example/domain/repository/OnboardingRepository.kt
Labels: FEAT ✨, 상호 🍀

#57 [Origin/#51] OnBoarding 추천인 코드
  app/src/main/java/com/yello/presentation/main/recommend/RecommendSchoolFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/nameid/NameIdFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/school/SchoolFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/school/university/SearchDialogSchoolFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/studentid/dialog/department/SearchDialogDepartmentFragment.kt
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_dialog_department.xml
  app/src/main/res/layout/fragment_dialog_school.xml
  app/src/main/res/layout/fragment_name_id.xml
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, PULL REQUEST 🚀, 민주 🌳

#60 [FEAT/#49] Local DB 구현 및 이슈 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/yello/di/DataSourceModule.kt
  app/src/main/java/com/yello/di/RepositoryModule.kt
  app/src/main/java/com/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileQuitDialog.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileQuitForSureActivity.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendKakaoFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendKakaoViewModel.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendSchoolFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendSchoolViewModel.kt
  app/src/main/java/com/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/yello/presentation/main/yello/dialog/UnlockDialogFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/lock/YelloLockFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/yello/presentation/main/yello/wait/YelloWaitFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/java/com/yello/presentation/splash/SplashActivity.kt
  app/src/main/java/com/yello/presentation/splash/SplashViewModel.kt
  data/src/main/java/com/example/data/datasource/VoteDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/VoteDataSourceImpl.kt
  data/src/main/java/com/example/data/local/YelloDataStoreImpl.kt
  data/src/main/java/com/example/data/model/request/onboarding/RequestPostSignupDto.kt
  data/src/main/java/com/example/data/model/request/vote/RequestPostVoteDto.kt
  data/src/main/java/com/example/data/remote/interceptor/AuthInterceptor.kt
  data/src/main/java/com/example/data/remote/service/VoteService.kt
  data/src/main/java/com/example/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/ProfileRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/RecommendRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/VoteRepositoryImpl.kt
  domain/src/main/java/com/example/domain/YelloDataStore.kt
  domain/src/main/java/com/example/domain/entity/onboarding/SignupInfo.kt
  domain/src/main/java/com/example/domain/repository/AuthRepository.kt
  domain/src/main/java/com/example/domain/repository/RecommendRepository.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 채연 🐸

#62 [UI/#61] 내 쪽지 리스트 없을 때 이미지 추가
  app/src/main/res/drawable/ic_empty_yello.xml
  app/src/main/res/layout/fragment_my_yello.xml
Labels: UI 💐, 강민 🦖

#65 [FIX/#59] onboarding 이슈 해결
  app/src/main/java/com/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/school/SchoolFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/school/university/SearchDialogSchoolFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/studentid/dialog/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/yello/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_dialog_department.xml
  app/src/main/res/layout/fragment_dialog_school.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#64 [FEAT/#63] 다이얼로그 이슈 해결 및 앱 재시작 구현
  app/src/debug/java/com/yello/FlipperSetUp.kt
  app/src/main/java/com/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileQuitActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileQuitDialog.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileQuitForSureActivity.kt
  app/src/main/java/com/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/remote/interceptor/AuthInterceptor.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 채연 🐸

#66 [FIX/#58] Recommend, Profile 이슈 대응
  app/src/main/java/com/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/yello/presentation/main/profile/info/ProfileFriendViewHolder.kt
  app/src/main/java/com/yello/presentation/main/profile/info/ProfileHeaderViewHolder.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/yello/presentation/main/profile/manage/ProfileQuitDialog.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendKakaoFragment.kt
  app/src/main/java/com/yello/presentation/main/recommend/RecommendSchoolFragment.kt
  app/src/main/java/com/yello/presentation/main/yello/dialog/UnlockDialogFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/yello/presentation/onboarding/fragment/gender/GenderFragment.kt
  app/src/main/java/com/yello/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_gender.xml
  app/src/main/res/layout/header_friends_list.xml
  app/src/main/res/layout/item_friends_list.xml
Labels: FIX 🔨, 상호 🍀

#71 [CHORE/#70] add official yello instagram id
  app/release/output-metadata.json
  app/src/main/res/layout/activity_my_yello_read.xml
  app/src/main/res/layout/fragment_note.xml
Labels: CHORE 🎀, PULL REQUEST 🚀, 채연 🐸

#73 [FIX/#72] 사용자 정보 로컬 저장 시점 변경
  app/src/main/java/com/el/yello/presentation/auth/SignInViewModel.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#76 [FIX/#75] 앱 스토어 로그인 오류 해결
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendDeleteBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendItemBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileHeaderViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileItemDecoration.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitDialog.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendItemDecoration.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendSchoolViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendViewPagerAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/yello/lock/YelloLockFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/point/PointFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/wait/YelloWaitFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/gender/GenderFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameIdFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/school/SchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/school/university/SearchDialogSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studentid/StudentIdFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studentid/dialog/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studentid/dialog/studentid/StudentidDialogFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayAdapter.kt
  app/src/main/java/com/el/yello/presentation/pay/PayEndActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayViewModel.kt
  app/src/main/java/com/el/yello/util/Utils.kt
  app/src/main/java/com/el/yello/util/binding/BindingAdapter.kt
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_gender.xml
  app/src/main/res/layout/fragment_name_id.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Constants.kt
Labels: HOTFIX 🚑️, PULL REQUEST 🚀, 채연 🐸

#82 [REFACTOR/#81] fake json 삭제
  data/src/main/assets/fake_check_keyword.json
  data/src/main/assets/fake_check_name.json
  data/src/main/assets/fake_detail_yello.json
  data/src/main/assets/fake_total_yello.json
Labels: REFACTOR ♻️, 강민 🦖

#85 [Hotfix/#83] 토큰 자동 재발급 구현
  data/build.gradle.kts
  data/src/main/java/com/example/data/model/response/onboarding/ResponseAuthToken.kt
  data/src/main/java/com/example/data/model/response/vote/ResponseGetVoteQuestionDto.kt
  data/src/main/java/com/example/data/remote/interceptor/AuthInterceptor.kt
Labels: HOTFIX 🚑️, 강민 🦖

#87 [FIX/#86] Recommend / 앱 종료 이슈 해결
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  buildSrc/src/main/kotlin/Constants.kt
Labels: FIX 🔨, 상호 🍀

#91 [HOTFIX/#90] 토큰 자동 재발급 수정
  app/build.gradle.kts
  app/src/release/java/com/el/yello/FlipperSetUp.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: HOTFIX 🚑️, 강민 🦖

#93 [CHORE/#92] Version Code 9
  buildSrc/src/main/kotlin/Constants.kt
Labels: CHORE 🎀, 강민 🦖

#89 [Refactor/#79] OnBoarding 전면 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/gender/GenderFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameIdFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/school/SchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/school/dialog/SchoolAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/school/dialog/SearchDialogSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studentid/StudentIdFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studentid/dialog/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studentid/dialog/studentId/StudentIdDialogAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studentid/dialog/studentId/StudentIdDialogFragment.kt
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_dialog_school.xml
  app/src/main/res/layout/fragment_school.xml
  app/src/main/res/layout/fragment_studentid.xml
Labels: PULL REQUEST 🚀, REFACTOR ♻️, 민주 🌳

#95 [FIX/#94] 내 쪽지 리스트 컬러 수정
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloAdapter.kt
  buildSrc/src/main/kotlin/Constants.kt
Labels: FIX 🔨, 강민 🦖
