Repository team-yello/YELLO-Android, pull requests merged in 2023-11, with the labels that each got.

#307 [CHORE/#292] build-logic 모듈 생성 및 version-catalog 적용
  app/build.gradle.kts
  build-logic/.gitignore
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/Constants.kt
  build-logic/convention/src/main/kotlin/ext/DependencyHandlerScopeExtension.kt
  build-logic/convention/src/main/kotlin/ext/ExtensionContainerExtension.kt
  build-logic/convention/src/main/kotlin/ext/VersionCatalogExtension.kt
  build-logic/convention/src/main/kotlin/ext/application/DefaultConfig.kt
  build-logic/convention/src/main/kotlin/plugins/AndroidApplicationPlugin.kt
  build-logic/convention/src/main/kotlin/plugins/AndroidHiltPlugin.kt
  build-logic/convention/src/main/kotlin/plugins/AndroidKotlinPlugin.kt
  build-logic/convention/src/main/kotlin/plugins/AndroidLibraryPlugin.kt
  build-logic/convention/src/main/kotlin/plugins/CommonConfigs.kt
  build-logic/settings.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core-ui/build.gradle.kts
  data/build.gradle.kts
  domain/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: CHORE 🎀, 강민 🦖

#320 [HOTFIX/#319] 회원가입 서버 통신 실패 시 예외 처리
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  gradle/libs.versions.toml
Labels: HOTFIX 🚑️, PULL REQUEST 🚀, 민주 🌳

#323 [FIX/#321] 내쪽지뷰 / 키워드 열람 시 서버통신 이후 값 표시되도록 수정
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointAfterDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointUseDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/ReadingTicketAfterDialog.kt
  app/src/main/res/layout/activity_my_yello_read.xml
  app/src/main/res/layout/dialog_point_after.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#325 [FIX/#324] 결제 뷰 / UI 수정 및 금액 조정
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileUserInfoViewHolder.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayInAppDialog.kt
  app/src/main/res/drawable/ic_shop_polygon.xml
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/fragment_my_yello.xml
  app/src/main/res/layout/item_profile_user_info.xml
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#328 [UI/#322] 시작하기 버튼 디자인 변경
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileItemDecoration.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/list/RecommendItemDecoration.kt
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/java/com/el/yello/presentation/search/SearchItemDecoration.kt
  app/src/main/res/layout/fragment_yello_start.xml
  app/src/main/res/values/strings.xml
  core-ui/src/main/java/com/example/ui/context/ContextExt.kt
  core-ui/src/main/java/com/example/ui/fragment/FragmentExt.kt
  core-ui/src/main/java/com/example/ui/intent/ExtraExt.kt
  core-ui/src/main/java/com/example/ui/number/IntExt.kt
Labels: PULL REQUEST 🚀, UI 💐, 채연 🐸

#330 [UI/#329] Yello / 옐로 시작하기 버튼 텍스트 속성 반영
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/res/drawable/shape_yello_main_500_fill_500_botshadow_rect.xml
  app/src/main/res/layout/fragment_yello_start.xml
  app/src/main/res/values/strings.xml
Labels: PULL REQUEST 🚀, UI 💐, 채연 🐸

#327 [UI/#326] 타임라인 뷰 UI 수정
  app/src/main/java/com/el/yello/presentation/main/look/LookViewHolder.kt
  app/src/main/res/drawable/ic_dot.xml
  app/src/main/res/layout/activity_my_yello_read.xml
  app/src/main/res/layout/item_look.xml
  app/src/main/res/layout/item_look_shimmer.xml
  app/src/main/res/layout/item_recommend_search.xml
  app/src/main/res/values/colors.xml
  build-logic/convention/src/main/kotlin/Constants.kt
  data/src/main/java/com/example/data/model/response/look/ResponseLookListDto.kt
  domain/src/main/java/com/example/domain/entity/LookListModel.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#332 [UI/#331] Tutorial / 튜토리얼 이미지 변경
  app/src/main/res/drawable/img_tutorial_a.xml
Labels: UI 💐, 민주 🌳

#334 [CHORE/#333] version code 36 변경
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: CHORE 🎀, 상호 🍀

#336 [FIX/#335] 결제정보 설명 수정
  README.md
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: FIX 🔨, 상호 🍀
