Repository team-yello/YELLO-Android, pull requests merged in 2023-09, with the labels that each got.

#224 FIX/#221 pull-to-refresh 적용 & 외부 QA 수정사항 대응
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchViewModel.kt
  app/src/main/res/layout/activity_my_yello_read.xml
  app/src/main/res/layout/activity_recommend_search.xml
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/layout/fragment_my_yello.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_recommend_school.xml
  app/src/main/res/layout/item_recommend_list.xml
  app/src/main/res/layout/item_recommend_search.xml
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#227 [FIX/#226] 내 쪽지 QA 반영
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
Labels: FIX 🔨, 강민 🦖

#229 [FIX/#228] 버전별 권한창 처리
  app/src/main/java/com/el/yello/presentation/onboarding/StartAppActivity.kt
Labels: FIX 🔨, 민주 🌳

#225 [FIX/#223] Yello & MyYello / 투표 전송 로직 보완 및 외부 QA 반영
  app/src/main/java/com/el/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/dialog/UnlockDialogFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/lock/YelloLockFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/res/layout/activity_my_yello_read.xml
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_yello_start.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#231 [CHORE/#230] version code 20 업데이트
  buildSrc/src/main/kotlin/Constants.kt
Labels: CHORE 🎀, 상호 🍀

#233 [FIX/#232] 버전 20 이슈 대응
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_recommend_school.xml
  app/src/main/res/layout/item_look.xml
  buildSrc/src/main/kotlin/Constants.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#237 [DEVELOP] PRODUCTION CI/CD
  .github/workflows/debug_builder.yml
  .github/workflows/pr_checker.yml
Labels: CHORE 🎀, 강민 🦖

#240 [FIX/#239] postsignup 호출 시점 변경
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
Labels: FIX 🔨, 민주 🌳

#246 [FIX/#242] MyYello / 내 쪽지 앰플리튜드 연결 마무리
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointUseDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/ReadingTicketUseDialog.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/res/layout/activity_my_yello_read.xml
  domain/src/main/java/com/example/domain/entity/YelloDetail.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#244 [FIX/#243] 구독권 구매 버튼 분기처리
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
Labels: FIX 🔨, 강민 🦖

#245 [FIX/#241] 글씨 크기 변경 대응
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointUseDialog.kt
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_dialog_department.xml
  app/src/main/res/layout/fragment_dialog_highschool.xml
  app/src/main/res/layout/fragment_dialog_university.xml
  app/src/main/res/layout/fragment_highschool.xml
  app/src/main/res/layout/fragment_university.xml
  app/src/main/res/layout/fragment_yello_id.xml
  app/src/main/res/layout/fragment_yello_lock.xml
  app/src/main/res/layout/item_highschool_list.xml
  app/src/main/res/layout/item_look.xml
  app/src/main/res/layout/item_pay_first.xml
  app/src/main/res/layout/item_pay_second.xml
  app/src/main/res/layout/item_pay_third.xml
  app/src/main/res/layout/item_recommend_list.xml
  app/src/main/res/layout/item_university_list.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Constants.kt
Labels: FIX 🔨, 상호 🍀

#249 [ADD/#248] Amplitude Userproperties 추가 및 수정
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/gender/GenderFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameFragment.kt
  app/src/main/res/layout/fragment_gender.xml
Labels: ADD ➕, FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#252 [REFACTOR/#247] Onboarding 2차 스프린트 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/GetAlarmActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendViewHolder.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/getAlarm/GetAlarmFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/studentid/StudentIdDialogFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/university/SearchDialogUniversityFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/university/UniversityAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/yelloid/YelIoIdFragment.kt
  app/src/main/res/layout/activity_get_alarm.xml
  app/src/main/res/layout/fragment_get_alarm.xml
  app/src/main/res/layout/fragment_name.xml
  app/src/main/res/navigation/activity_navigate.xml
Labels: PULL REQUEST 🚀, REFACTOR ♻️, 민주 🌳

#253 [FIX/#250] Note, MyYello / 앰플리튜드 QA 반영
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointAfterDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/ReadingTicketAfterDialog.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteActivity.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteFragment.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#251 [REFACTOR/#238] 2차 스프린트 리팩토링
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/el/yello/presentation/main/dialog/InviteFriendDialog.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendDeleteBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendItemBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitDialog.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitTwoActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/dialog/UnlockDialogFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/lock/YelloLockFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/wait/YelloWaitFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/PayViewModel.kt
  app/src/main/java/com/el/yello/util/Utils.kt
  app/src/main/res/layout/fragment_invite_friend_dialog.xml
  app/src/main/res/layout/fragment_unlock_dialog.xml
  buildSrc/src/main/kotlin/Constants.kt
  data/src/main/java/com/example/data/datasource/paging/LookPagingSource.kt
  data/src/main/java/com/example/data/repository/OnboardingRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/PayRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/ProfileRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/RecommendRepositoryImpl.kt
  domain/src/main/java/com/example/domain/repository/OnboardingRepository.kt
  domain/src/main/java/com/example/domain/repository/PayRepository.kt
  domain/src/main/java/com/example/domain/repository/ProfileRepository.kt
  domain/src/main/java/com/example/domain/repository/RecommendRepository.kt
Labels: PULL REQUEST 🚀, REFACTOR ♻️, 상호 🍀

#259 [FIX/#258] onBackClicked() 함수 타입 롤백
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#265 [CHORE/#264] version code 25 업데이트
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  buildSrc/src/main/kotlin/Constants.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#268 [FIX/#267] 온보딩->카톡 로직 수정
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#270 [CHORE/#269] version code 26 업데이트
  buildSrc/src/main/kotlin/Constants.kt
Labels: CHORE 🎀, PULL REQUEST 🚀, 상호 🍀

#273 [FIX/#272] 푸시알림 Null 분기처리
  app/src/main/java/com/el/yello/config/YelloMessagingService.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: FIX 🔨, 강민 🦖

#271 [FIX/#263] Auth / 카카오 친구목록 동의 시 뷰 스킵하기
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayViewModel.kt
  buildSrc/src/main/kotlin/Constants.kt
  data/src/main/java/com/example/data/datasource/YelloDataSource.kt
  data/src/main/java/com/example/data/datasource/local/MockYelloDataSourceImpl.kt
  data/src/main/java/com/example/data/datasource/remote/YelloDataSourceImpl.kt
  data/src/main/java/com/example/data/model/request/RequestPayIndexDto.kt
  data/src/main/java/com/example/data/remote/service/YelloService.kt
  data/src/main/java/com/example/data/repository/YelloRepositoryImpl.kt
  domain/src/main/java/com/example/domain/repository/YelloRepository.kt
Labels: FIX 🔨, 상호 🍀

#275 [CHORE/#274] version name 1.3 업데이트
  buildSrc/src/main/kotlin/Constants.kt
Labels: CHORE 🎀, PULL REQUEST 🚀, 상호 🍀

#278 [FIX/#277] Splash / 인터넷 불안정 시 Dialog
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/splash/SplashActivity.kt
  app/src/main/java/com/el/yello/util/NetworkManager.kt
  app/src/main/res/layout/activity_splash.xml
Labels: FIX 🔨, 강민 🦖

#280 [FIX/#279] Crypto Library 제거
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  data/build.gradle.kts
  data/src/main/java/com/example/data/local/YelloDataStoreImpl.kt
Labels: FIX 🔨, 강민 🦖

#281 [FIX/#276] Yello / 투표 시작 화면 크래시 오류 해결 및 4명 이하 말풍선 적용 시점 확인
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/list/RecommendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  buildSrc/src/main/kotlin/Constants.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#287 [HOTFIX/#286] security remove
  app/build.gradle.kts
  app/src/main/java/com/el/yello/di/DataStoreModule.kt
  buildSrc/src/main/kotlin/Constants.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  data/build.gradle.kts
Labels: HOTFIX 🚑️, 강민 🦖

#290 [HOTFIX/#289] google play 리젝 해결
  app/build.gradle.kts
  app/src/main/java/com/el/yello/di/DataStoreModule.kt
  app/src/main/java/com/el/yello/presentation/splash/SplashActivity.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  data/build.gradle.kts
Labels: HOTFIX 🚑️, 강민 🦖
