Repository team-yello/YELLO-Android, pull requests merged in 2023-10, with the labels that each got.

#291 [CHORE/#261] libs.versions.toml 생성
  gradle/libs.versions.toml
Labels: CHORE 🎀, 강민 🦖

#297 [HOTFIX/#296] gradient angle 45배수 적용
  app/src/main/res/drawable/shape_gradient_vote_bg_01.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_02.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_03.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_04.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_05.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_06.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_07.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_08.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_09.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_10.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_11.xml
  app/src/main/res/drawable/shape_gradient_vote_bg_12.xml
Labels: HOTFIX 🚑️, PULL REQUEST 🚀, 채연 🐸

#299 [CHORE/#298] version code 32 업데이트
  buildSrc/src/main/kotlin/Constants.kt
Labels: CHORE 🎀, PULL REQUEST 🚀, 상호 🍀

#293 [MOD/#288] OnBoarding / Refactoring & StateFlow
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/GetAlarmActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/getAlarm/GetAlarmFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/school/SearchDialogHighSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studenttype/SelectStudentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/university/SearchDialogUniversityFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/university/UniversityAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/yelloid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialAActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialBActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialCActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialDActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndPlusActivity.kt
  app/src/main/res/layout/activity_get_alarm.xml
  app/src/main/res/layout/fragment_add_friend.xml
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_get_alarm.xml
  app/src/main/res/layout/fragment_highschool.xml
  app/src/main/res/layout/fragment_select_student_type.xml
  app/src/main/res/layout/fragment_university.xml
  app/src/main/res/layout/fragment_yello_id.xml
  app/src/main/res/layout/item_university_list.xml
  app/src/main/res/navigation/activity_navigate.xml
Labels: MOD ✅, PULL REQUEST 🚀, 민주 🌳

#295 [REFACTOR/#80] Yello / 플로우 반영 및 전반적 리팩토링
  app/src/main/java/com/el/yello/presentation/main/dialog/InviteFriendDialog.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/point/PointFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteActivity.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/wait/YelloWaitFragment.kt
  domain/src/main/java/com/example/domain/entity/PayInfoModel.kt
Labels: PULL REQUEST 🚀, REFACTOR ♻️, 채연 🐸

#303 [ADD/#301] OnBoarding / 학력 선택, 고등학교 Amplitude, User Properties 추가 & flowWithLifecycle 적용
  app/src/main/java/com/el/yello/presentation/onboarding/activity/GetAlarmActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/HighSchoolInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/school/SearchDialogHighSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studenttype/SelectStudentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/university/SearchDialogUniversityFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/yelloid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialAActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialBActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialCActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialDActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndPlusActivity.kt
Labels: ADD ➕, PULL REQUEST 🚀, 민주 🌳

#304 [FIX/#300,#302] Domain 레이어 Paging3 제거 & FlowWithLifecycle 적용
  app/src/main/java/com/el/yello/di/RepositoryModule.kt
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendDeleteBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendItemBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitDialog.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitOneActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitTwoActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/BillingManager.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayViewModel.kt
  app/src/main/java/com/el/yello/presentation/search/SearchActivity.kt
  app/src/main/java/com/el/yello/presentation/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_profile_delete_bottom_sheet.xml
  app/src/main/res/layout/fragment_profile_item_bottom_sheet.xml
  app/src/main/res/layout/item_profile_user_info.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/repository/LookRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/ProfileUserModel.kt
  domain/src/main/java/com/example/domain/repository/LookRepository.kt
  domain/src/main/java/com/example/domain/repository/PayRepository.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#309 [FIX/#308] 추천친구 뷰 친구추가 애니메이션 재설정
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#313 [FIX/#311] 셔플 및 키워드 오픈 직후 초성 오픈 이슈 해결
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointAfterDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointUseDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/ReadingTicketAfterDialog.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#314 [CHORE/#310] version code 33 업데이트
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/list/RecommendAdapter.kt
  buildSrc/src/main/kotlin/Constants.kt
Labels: CHORE 🎀, PULL REQUEST 🚀, 상호 🍀
