Repository team-yello/YELLO-Android, pull requests merged in 2023-08, with the labels that each got.

#101 [CHORE/#100] 깃허브 action secrets 추가
  .github/workflows/debug_builder.yml
  .github/workflows/pr_checker.yml
Labels: CHORE 🎀, PULL REQUEST 🚀, 채연 🐸

#104 [FEAT/#103] 투표하기 개수 동적으로 변경
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteActivity.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/res/layout/fragment_note.xml
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
Labels: FEAT ✨, 강민 🦖

#106 [FEAT/#105] 옐로 버튼 애니메이션 커스텀 뷰 제작
  app/src/main/java/com/el/yello/presentation/util/GradientButton.kt
  app/src/main/java/com/el/yello/presentation/util/GradientStrokeButton.kt
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
Labels: FEAT ✨, 강민 🦖

#109 [CHORE/#108] Firebase Gradle Setting
  .github/workflows/pr_checker.yml
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: CHORE 🎀, 강민 🦖

#110 [FIX/#107] 로그인, 회원가입 서버통신에 device token 추가
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  data/src/main/java/com/example/data/local/YelloDataStoreImpl.kt
  data/src/main/java/com/example/data/model/request/onboarding/RequestPostSignupDto.kt
  data/src/main/java/com/example/data/model/request/onboarding/RequestServiceTokenDto.kt
  data/src/main/java/com/example/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/example/domain/YelloDataStore.kt
  domain/src/main/java/com/example/domain/entity/RequestServiceTokenModel.kt
  domain/src/main/java/com/example/domain/entity/onboarding/SignupInfo.kt
  domain/src/main/java/com/example/domain/repository/AuthRepository.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#113 [UI/#102] 스켈레톤 로딩 대기화면 구현
  app/build.gradle.kts
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/dialog/UnlockDialogFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/ViewPagerAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendViewHolder.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameIdFragment.kt
  app/src/main/res/drawable/shape_shimmer_greyscale800_circle.xml
  app/src/main/res/drawable/shape_shimmer_greyscale800_fill_2_rect.xml
  app/src/main/res/drawable/shape_shimmer_greyscale_off_fill_2_rect.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_social_sync.xml
  app/src/main/res/layout/fragment_add_friend.xml
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_recommend_school.xml
  app/src/main/res/layout/item_add_friend.xml
  app/src/main/res/layout/item_add_friend_shimmer.xml
  app/src/main/res/layout/item_profile_friends_list.xml
  app/src/main/res/layout/item_profile_user_info.xml
  app/src/main/res/layout/item_recommend_list.xml
  app/src/main/res/layout/item_recommend_list_shimmer.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core-ui/src/main/java/com/example/ui/base/BindingDialogFragment.kt
Labels: PULL REQUEST 🚀, UI 💐, 상호 🍀

#115 [FEAT/#114] 푸시알림(FCM) 개발
  .github/workflows/debug_builder.yml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/config/YelloMessagingService.kt
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, 강민 🦖

#116 [UI/#99] 둘러보기 뷰 구현
  app/src/main/java/com/el/yello/di/DataSourceModule.kt
  app/src/main/java/com/el/yello/di/RepositoryModule.kt
  app/src/main/java/com/el/yello/di/ServiceModule.kt
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendItemBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/list/RecommendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/dialog/UnlockDialogFragment.kt
  app/src/main/res/drawable/ic_look_right_arrow.xml
  app/src/main/res/drawable/img_look.xml
  app/src/main/res/drawable/shape_grayscales800_fill_grayscales700_dashline_4_rect.xml
  app/src/main/res/drawable/shape_shimmer_grayscale600_circle.xml
  app/src/main/res/drawable/shape_shimmer_grayscale700_fill_2_rect.xml
  app/src/main/res/layout/activity_profile_quit.xml
  app/src/main/res/layout/fragment_gender.xml
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/layout/fragment_my_yello.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/fragment_recommend_invite_dialog.xml
  app/src/main/res/layout/fragment_unlock_dialog.xml
  app/src/main/res/layout/item_look.xml
  app/src/main/res/layout/item_look_shimmer.xml
  app/src/main/res/layout/item_profile_user_info.xml
  app/src/main/res/layout/item_recommend_list.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/datasource/LookDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/LookDataSourceImpl.kt
  data/src/main/java/com/example/data/model/response/look/ResponseLookListDto.kt
  data/src/main/java/com/example/data/remote/service/LookService.kt
  data/src/main/java/com/example/data/repository/LookRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/LookListModel.kt
  domain/src/main/java/com/example/domain/repository/LookRepository.kt
Labels: PULL REQUEST 🚀, UI 💐, 상호 🍀

#120 [Feat/#112] OnBoarding / Debounce 및 Navigation 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/onboarding/ViewPagerAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/gender/GenderFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/HighschoolInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameIdFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studenttype/SelectStudentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/school/SearchDialogSchoolFragment.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_add_friend.xml
  app/src/main/res/layout/fragment_gender.xml
  app/src/main/res/layout/fragment_highschool.xml
  app/src/main/res/layout/fragment_name_id.xml
  app/src/main/res/layout/fragment_select_student_type.xml
  app/src/main/res/layout/fragment_start_app.xml
  app/src/main/res/layout/fragment_university.xml
  app/src/main/res/layout/item_department_list.xml
  app/src/main/res/layout/item_group_list.xml
  app/src/main/res/layout/item_highschool_list.xml
  app/src/main/res/layout/item_studentid_list.xml
  app/src/main/res/layout/item_university_list.xml
  app/src/main/res/navigation/activity_navigate.xml
  build.gradle.kts
Labels: FEAT ✨, PULL REQUEST 🚀, 민주 🌳

#122 [FEAT/#119] 푸시알림 세부 구현
  app/src/main/java/com/el/yello/config/YelloMessagingService.kt
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/splash/SplashActivity.kt
Labels: FEAT ✨, 강민 🦖

#124 [UI/#118] OnBoarding / 온보딩 3차 수정사항
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/gender/GenderFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/HighschoolInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studenttype/SelectStudentFragment.kt
  app/src/main/res/drawable/ic_onboarding_name_yello_bubble.xml
  app/src/main/res/drawable/ic_onboarding_school_yello_bubble.xml
  app/src/main/res/drawable/ic_onboarding_startapp_heart.xml
  app/src/main/res/drawable/ic_onboarding_yelloid_yelli_bubble.xml
  app/src/main/res/drawable/ic_student_highschool_face_default.xml
  app/src/main/res/drawable/ic_student_highschool_face_select.xml
  app/src/main/res/drawable/ic_student_highschool_face_unselected.xml
  app/src/main/res/drawable/ic_student_university_face_default.xml
  app/src/main/res/drawable/ic_student_university_face_select.xml
  app/src/main/res/drawable/ic_student_university_face_unselected.xml
  app/src/main/res/drawable/sel_onbarding_editext_focus.xml
  app/src/main/res/drawable/shape_grayscales800_fill_grayscales700_line_8_rect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_grayscales700_line_8_leftrect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_grayscales700_line_8_rightrect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_grayscales700_line_8_square.xml
  app/src/main/res/drawable/shape_grayscales900_fill_yello_main600_line_8_leftrect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_yello_main600_line_8_rightrect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_yello_main600_line_8_square.xml
  app/src/main/res/layout/fragment_add_friend.xml
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_dialog_department.xml
  app/src/main/res/layout/fragment_dialog_highschool.xml
  app/src/main/res/layout/fragment_dialog_university.xml
  app/src/main/res/layout/fragment_highschool.xml
  app/src/main/res/layout/fragment_name.xml
  app/src/main/res/layout/fragment_select_student_type.xml
  app/src/main/res/layout/fragment_start_app.xml
  app/src/main/res/layout/fragment_university.xml
  app/src/main/res/layout/fragment_yello_id.xml
  app/src/main/res/navigation/activity_navigate.xml
  app/src/main/res/values/strings.xml
Labels: PULL REQUEST 🚀, UI 💐, 민주 🌳

#129 [FEAT/#128] 공통 다이얼로그 UI 수정
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointAfterDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointUseDialog.kt
  app/src/main/res/layout/dialog_point_after.xml
  app/src/main/res/layout/dialog_point_use.xml
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, 강민 🦖

#127 [FEAT/#126] 내 쪽지 리스트 화면 변경점 구현
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/util/GradientButton.kt
  app/src/main/java/com/el/yello/presentation/util/GradientStrokeButton.kt
  app/src/main/res/drawable/ic_key.xml
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_shop.xml
  app/src/main/res/drawable/shape_fill_yello500_100dp.xml
  app/src/main/res/layout/fragment_my_yello.xml
  app/src/main/res/layout/item_my_yello_shimmer.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/model/response/yello/ResponseMyYello.kt
  domain/src/main/java/com/example/domain/entity/MyYello.kt
Labels: FEAT ✨, 강민 🦖

#133 [FIX/#132] Manifest에 billing 추가
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/Constants.kt
Labels: FIX 🔨, 상호 🍀

#135 [Feat/#125] onboarding / UI 수정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/gender/GenderFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/HighschoolInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/school/SearchDialogHighSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studenttype/SelectStudentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/school/SearchDialogSchoolFragment.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_profile_quit_for_sure.xml
  app/src/main/res/layout/activity_recommend_search.xml
  app/src/main/res/layout/fragment_add_friend.xml
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_dialog_department.xml
  app/src/main/res/layout/fragment_dialog_group.xml
  app/src/main/res/layout/fragment_dialog_highschool.xml
  app/src/main/res/layout/fragment_dialog_student_id.xml
  app/src/main/res/layout/fragment_dialog_university.xml
  app/src/main/res/layout/fragment_gender.xml
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/layout/fragment_name.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_recommend_school.xml
  app/src/main/res/layout/fragment_select_student_type.xml
  app/src/main/res/layout/fragment_university.xml
  app/src/main/res/layout/fragment_yello_id.xml
  app/src/main/res/navigation/activity_navigate.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: ADD ➕, PULL REQUEST 🚀, 민주 🌳

#134 [FEAT/#123] 검색, 둘러보기 페이징 구현 & UI 수정 대응
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/di/DataSourceModule.kt
  app/src/main/java/com/el/yello/di/RepositoryModule.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileUserInfoViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitOneActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitTwoActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchViewModel.kt
  app/src/main/java/com/el/yello/presentation/util/GradientStrokeButton.kt
  app/src/main/res/drawable/ic_no_search.xml
  app/src/main/res/drawable/ic_point_zero.xml
  app/src/main/res/drawable/ic_search_loading.xml
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/drawable/shape_black_fill_grayscales700_line_100_rect.xml
  app/src/main/res/drawable/shape_grayscales800_fill_100_rect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_100_rect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_12_rect.xml
  app/src/main/res/layout/activity_profile_quit_for_sure.xml
  app/src/main/res/layout/activity_profile_quit_one.xml
  app/src/main/res/layout/activity_profile_quit_two.xml
  app/src/main/res/layout/activity_recommend_search.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_recommend_school.xml
  app/src/main/res/layout/item_profile_friends_list.xml
  app/src/main/res/layout/item_profile_user_info.xml
  app/src/main/res/layout/item_recommend_list.xml
  app/src/main/res/layout/item_recommend_list_shimmer.xml
  app/src/main/res/layout/item_recommend_search.xml
  app/src/main/res/raw/lottie_spinner_loading.json
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Constants.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  data/build.gradle.kts
  data/src/main/java/com/example/data/datasource/LookDataSource.kt
  data/src/main/java/com/example/data/datasource/RecommendDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/LookDataSourceImpl.kt
  data/src/main/java/com/example/data/datasource/remote/LookPagingSource.kt
  data/src/main/java/com/example/data/datasource/remote/RecommendDataSourceImpl.kt
  data/src/main/java/com/example/data/remote/service/RecommendService.kt
  data/src/main/java/com/example/data/repository/LookRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/RecommendRepositoryImpl.kt
  domain/src/main/java/com/example/domain/repository/LookRepository.kt
  domain/src/main/java/com/example/domain/repository/RecommendRepository.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 상호 🍀

#138 [FEAT/#137] 온보딩 progressbar animation 구현
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
Labels: FEAT ✨, 강민 🦖

#140 [FEAT/#139] 안읽은 쪽지 서버통신 구현
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  data/src/main/java/com/example/data/datasource/YelloDataSource.kt
  data/src/main/java/com/example/data/datasource/local/MockYelloDataSourceImpl.kt
  data/src/main/java/com/example/data/datasource/remote/YelloDataSourceImpl.kt
  data/src/main/java/com/example/data/model/response/vote/ResponseVoteCount.kt
  data/src/main/java/com/example/data/remote/service/YelloService.kt
  data/src/main/java/com/example/data/repository/YelloRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/vote/VoteCount.kt
  domain/src/main/java/com/example/domain/repository/YelloRepository.kt
Labels: FEAT ✨, 강민 🦖

#147 [CHORE/#146] amplitude 기초 세팅
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: 민주 🌳

#150 [CHORE/#149] CI amplitude
  .github/workflows/pr_checker.yml
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: CHORE 🎀, 강민 🦖

#152 [CHORE/#146] Amplitude 초기 설정
  app/src/main/java/com/el/yello/MyApp.kt
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/util/amplitude/Amplitude.kt
Labels: CHORE 🎀, 민주 🌳

#153 [FEAT/#145] 전체적인 UI 수정
  app/build.gradle.kts
  app/src/main/java/com/el/yello/MyApp.kt
  app/src/main/java/com/el/yello/presentation/onboarding/StartAppActivity.kt
  app/src/main/res/drawable/shape_kakao_100_rect.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_social_sync.xml
  app/src/main/res/layout/activity_tutorial_end_pluspoint.xml
  app/src/main/res/layout/activity_tutorial_end_point.xml
  app/src/main/res/layout/fragment_start_app.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/strings.xml
Labels: PULL REQUEST 🚀, UI 💐, 민주 🌳

#157 [FEAT/#156] 뷰페이저 자동 스크롤 구현
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
Labels: FEAT ✨, 강민 🦖

#159 [FEAT/#158] 읽은 처리 로직 수정
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloAdapter.kt
Labels: FEAT ✨, 강민 🦖

#161 [UI/#143] Yello / 바텀 내비게이션 옐로 아이콘 커스텀
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/res/drawable/ic_main_look_selected.xml
  app/src/main/res/drawable/ic_main_my_yello_selected.xml
  app/src/main/res/drawable/ic_main_profile_selected.xml
  app/src/main/res/drawable/ic_main_recommend_selected.xml
  app/src/main/res/drawable/ic_main_yello_active.xml
  app/src/main/res/drawable/ic_main_yello_selected.xml
  app/src/main/res/drawable/ic_main_yello_unselected.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/layout/fragment_profile_delete_bottom_sheet.xml
  app/src/main/res/layout/fragment_profile_item_bottom_sheet.xml
  app/src/main/res/layout/fragment_yello_start.xml
  app/src/main/res/layout/item_add_friend.xml
  app/src/main/res/layout/item_profile_friends_list.xml
  app/src/main/res/layout/item_profile_user_info.xml
  app/src/main/res/layout/item_recommend_list.xml
  app/src/main/res/layout/item_recommend_search.xml
Labels: PULL REQUEST 🚀, UI 💐, 채연 🐸

#163 [FEAT/#162] 내 쪽지 Amplitude
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointUseDialog.kt
Labels: FEAT ✨, 강민 🦖

#164 [Feat/#154] Amplitude 추가
  app/build.gradle.kts
  app/src/main/java/com/el/yello/MyApp.kt
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/StartAppActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialAActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialBActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialCActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialDActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndPlusActivity.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 민주 🌳

#168 [CHORE/#167] CI Amplitude DEBUG/RELEASE 분기처리
  .github/workflows/pr_checker.yml
Labels: CHORE 🎀, 강민 🦖

#165 [FEAT/#151] 인앱결제 서버통신 임시 해제 & amplitude 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitDialog.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitOneActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitTwoActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayEndActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayViewModel.kt
  app/src/main/res/layout/activity_pay_end.xml
  app/src/main/res/layout/fragment_unlock_dialog.xml
  app/src/main/res/layout/fragment_yello_wait.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Constants.kt
  data/src/main/java/com/example/data/datasource/PayDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/PayDataSourceImpl.kt
  data/src/main/java/com/example/data/model/response/pay/ResponsePurchaseInfoDto.kt
  data/src/main/java/com/example/data/model/response/pay/ResponseSubsNeededDto.kt
  data/src/main/java/com/example/data/remote/service/PayService.kt
  data/src/main/java/com/example/data/repository/PayRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/ResponsePurchaseInfoModel.kt
  domain/src/main/java/com/example/domain/entity/ResponseSubsNeededModel.kt
  domain/src/main/java/com/example/domain/repository/PayRepository.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 상호 🍀

#171 [FIX/#169] 추천친구 뷰, 다이얼로그 amplitude 수정
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/dialog/UnlockDialogFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/lock/YelloLockFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/wait/YelloWaitFragment.kt
  app/src/main/res/drawable/ic_empty_yello.xml
  app/src/main/res/drawable/img_lock_vote.xml
  app/src/main/res/drawable/img_vote_no_friend.xml
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/layout/fragment_my_yello.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/layout/fragment_recommend_kakao.xml
  app/src/main/res/layout/fragment_yello_lock.xml
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#173 [FIX/#172] Typo 및 amplitude 수정
  app/src/main/java/com/el/yello/presentation/onboarding/StartAppActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/res/layout/activity_profile_quit_one.xml
  app/src/main/res/layout/activity_profile_quit_two.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_social_sync.xml
  app/src/main/res/layout/activity_start_app.xml
  app/src/main/res/layout/activity_tutorial_end_pluspoint.xml
  app/src/main/res/layout/activity_tutorial_end_point.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/layout/fragment_start_app.xml
  app/src/main/res/layout/fragment_yello_lock.xml
  app/src/main/res/layout/fragment_yello_wait.xml
  app/src/main/res/values/strings.xml
Labels: UI 💐, 민주 🌳

#176 [FEAT/#174] 인앱 업데이트 구현
  app/build.gradle.kts
  app/src/main/java/com/el/yello/presentation/splash/SplashActivity.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: FEAT ✨, 강민 🦖

#178 [FIX/#177] 인앱 업데이트 분기처리 & 내옐로 Dto 수정
  app/src/main/java/com/el/yello/MyApp.kt
  app/src/main/java/com/el/yello/presentation/splash/SplashActivity.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/model/response/yello/ResponseMyYello.kt
  data/src/main/java/com/example/data/repository/YelloRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/MyYello.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#180 [CHORE/#179] CD TEST
  .github/workflows/debug_builder.yml
Labels: CHORE 🎀, 강민 🦖

#183 [FIX/#175] 푸쉬 알림 권한 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/StartAppActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/java/com/el/yello/util/amplitude/Amplitude.kt
  app/src/main/res/layout/activity_profile_quit_one.xml
Labels: FIX 🔨, 민주 🌳

#182 [FEAT/#181] Paging3 빈 데이터 분기처리
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
Labels: FEAT ✨, 강민 🦖

#170 [FEAT/#143] Yello / 투표 진행 상황 로컬 저장
  app/build.gradle.kts
  app/src/main/java/com/el/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteActivity.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteFragment.kt
  app/src/main/res/layout/fragment_note.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  data/build.gradle.kts
  data/src/main/java/com/example/data/local/YelloDataStoreImpl.kt
  data/src/main/java/com/example/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/VoteRepositoryImpl.kt
  domain/src/main/java/com/example/domain/YelloDataStore.kt
  domain/src/main/java/com/example/domain/entity/vote/StoredVote.kt
  domain/src/main/java/com/example/domain/repository/VoteRepository.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 채연 🐸

#185 [FEAT/#166] 결제 뷰 수정 대응 & 미완성 부분 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/point/PointFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayEndActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayInAppDialog.kt
  app/src/main/java/com/el/yello/presentation/pay/PaySubsDialog.kt
  app/src/main/java/com/el/yello/presentation/pay/PayViewModel.kt
  app/src/main/java/com/el/yello/presentation/util/BillingManager.kt
  app/src/main/res/layout/activity_pay_end.xml
  app/src/main/res/layout/fragment_my_yello.xml
  app/src/main/res/layout/fragment_note.xml
  app/src/main/res/layout/fragment_pay_in_app_dialog.xml
  app/src/main/res/layout/fragment_pay_subs_dialog.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/layout/fragment_yello_start.xml
  data/src/main/java/com/example/data/model/response/yello/ResponseMyYello.kt
  domain/src/main/java/com/example/domain/entity/MyYello.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 상호 🍀

#186 [FIX/#184] Userproperties
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/gender/GenderFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/util/amplitude/Amplitude.kt
Labels: FEAT ✨, 민주 🌳

#190 [ADD/#187] 서버통신 관련 User properties amplitude 추가
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
Labels: ADD ➕, PULL REQUEST 🚀, 민주 🌳

#195 [FEAT/#194] 내 첫 쪽지 상세보기 분기처리
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
Labels: FEAT ✨, 강민 🦖

#198 [CHORE/#197] README 2차 스프린트 대응
  README.md
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncActivity.kt
Labels: CHORE 🎀, PULL REQUEST 🚀, 상호 🍀

#199 [FIX/#194] OnBoarding / 2차 QA 대응
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/YelIoIdFragment.kt
  app/src/main/res/drawable/ic_onboarding_yelloid_bubble.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_yello_id.xml
  app/src/main/res/layout/item_add_friend.xml
  app/src/main/res/navigation/activity_navigate.xml
Labels: FIX 🔨, 민주 🌳

#201 [FIX/#192] 2차 QA 대응
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendDeleteBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendItemBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendsListViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileUserInfoViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitTwoActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/RecommendInviteDialog.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/list/RecommendViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/yello/dialog/UnlockDialogFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayInAppDialog.kt
  app/src/main/java/com/el/yello/presentation/pay/PaySubsDialog.kt
  app/src/main/res/drawable/img_yello_basic.xml
  app/src/main/res/drawable/img_yello_dummy.xml
  app/src/main/res/layout/fragment_pay_in_app_dialog.xml
  app/src/main/res/layout/fragment_pay_subs_dialog.xml
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#203 [FIX/#200] 온보딩 2차 QA 대응
  app/src/main/java/com/el/yello/presentation/onboarding/StartAppActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/nameid/NameFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialAActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialBActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialCActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialDActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndPlusActivity.kt
  app/src/main/res/drawable/sel_onboarding_studentid.xml
  app/src/main/res/layout/item_studentid_list.xml
  data/src/main/java/com/example/data/remote/service/OnboardingService.kt
Labels: FIX 🔨, 민주 🌳

#207 [FIX/#206] 내 쪽지 QA 대응
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointUseDialog.kt
  app/src/main/res/layout/activity_my_yello_read.xml
  app/src/main/res/layout/item_my_yello.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/datasource/remote/OnboardingDataSourceImpl.kt
Labels: FIX 🔨, 강민 🦖

#205 [FIX/#202] 투표 뷰 QA 대응
  app/src/main/java/com/el/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/point/PointFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/res/layout/fragment_note.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/layout/fragment_yello_start.xml
  buildSrc/src/main/kotlin/Constants.kt
  data/src/main/java/com/example/data/datasource/OnboardingDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/OnboardingDataSourceImpl.kt
  data/src/main/java/com/example/data/remote/service/PayService.kt
  data/src/main/java/com/example/data/repository/OnboardingRepositoryImpl.kt
  domain/src/main/java/com/example/domain/repository/OnboardingRepository.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#208 [FIX/#204] 온보딩 알림 받기뷰 이슈
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/res/layout/activity_tutorial_end_pluspoint.xml
  app/src/main/res/layout/activity_tutorial_end_point.xml
Labels: FIX 🔨, 민주 🌳

#213 [FEAT/#211] 디바이스 토큰 업데이트 구현
  app/src/main/java/com/el/yello/config/YelloMessagingService.kt
  app/src/main/java/com/el/yello/di/DataSourceModule.kt
  app/src/main/java/com/el/yello/di/ServiceModule.kt
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  data/src/main/java/com/example/data/datasource/AuthDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/AuthDataSourceImpl.kt
  data/src/main/java/com/example/data/model/request/auth/RequestDeviceDto.kt
  data/src/main/java/com/example/data/remote/service/AuthService.kt
  data/src/main/java/com/example/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/example/domain/repository/AuthRepository.kt
Labels: FEAT ✨, 강민 🦖

#210 [FIX/#209] 열람권 사용 시 리스트로 돌아왔을 때 개수 반영
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
Labels: FIX 🔨, 강민 🦖

#215 [FIX/#214] 열람권 결제 API 수정
  data/src/main/java/com/example/data/remote/service/PayService.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#217 [FIX/#216] 1.2 버전 수정사항 대응
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendDeleteBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendItemBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendsListViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileUserInfoViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/list/RecommendViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/search/RecommendSearchViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/start/YelloStartFragment.kt
  app/src/main/res/layout/activity_profile_manage.xml
  app/src/main/res/layout/fragment_yello_start.xml
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#222 [FIX/#220] Tutorial / 외부 QA 반영
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/startapp/StartAppFragment.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialAActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialBActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialCActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialDActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndPlusActivity.kt
Labels: FIX 🔨, 민주 🌳
