Repository team-yello/YELLO-Android, pull requests merged in 2024-04, with the labels that each got.

#434 [FIX/#433] Pay / 결제 검증 중 뒤로가기 방지
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: FIX 🔨, 상호 🍀

#436 [FIX/#435] 상점 관련 Amplitude 수정 및 중학교 userProperties 추가
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/auth/SignInViewModel.kt
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/el/yello/presentation/main/dialog/invite/InviteFriendDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/PointUseDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/ReadingTicketAfterDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/ReadingTicketUseDialog.kt
  app/src/main/java/com/el/yello/presentation/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studenttype/SelectStudentFragment.kt
  app/src/main/java/com/el/yello/presentation/search/SearchActivity.kt
  app/src/main/java/com/el/yello/presentation/search/SearchViewModel.kt
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitDialog.kt
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitOneActivity.kt
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitReasonActivity.kt
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitTwoActivity.kt
  app/src/main/java/com/el/yello/presentation/setting/SettingActivity.kt
  app/src/main/java/com/el/yello/presentation/setting/SettingViewModel.kt
  app/src/main/java/com/el/yello/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_select_student_type.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/example/domain/enum/StudentType.kt
Labels: ADD ➕, FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#440 [ FIX/#438] 구독 정보 조회 expiredDate Empty, Null 처리 추가
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#439 [FIX/#437] Yello / index out of bounds 예외 처리
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteActivity.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#442 [MOD/#441] Pay / 옐로 상품 가격 조정
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: MOD ✅, 상호 🍀
