Repository team-yello/YELLO-Android, pull requests merged in 2024-02, with the labels that each got.

#358 [REFACTOR/#348] OnBoarding / 튜토리얼 변경 및 리팩토링
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/EditNameActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendViewHolder.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/checkName/CheckNameDialog.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/HighSchoolInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/school/HighSchoolAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/school/SearchDialogHighSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studenttype/SelectStudentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/department/DepartmentAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/university/UniversityAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/yelloid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialAActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialBActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialCActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialDActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndActivity.kt
  app/src/main/java/com/el/yello/presentation/tutorial/TutorialEndPlusActivity.kt
  app/src/main/res/drawable/img_tutorial_a.xml
  app/src/main/res/drawable/img_tutorial_b.xml
  app/src/main/res/drawable/img_tutorial_c.xml
  app/src/main/res/drawable/img_tutorial_d.xml
  app/src/main/res/layout/fragment_dialog_check_name.xml
  app/src/main/res/layout/fragment_highschool.xml
Labels: PULL REQUEST 🚀, REFACTOR ♻️, UI 💐, 민주 🌳

#361 [FEAT/#352] Timeline / 타임라인 목록 필터 구현
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/shape_grayscales800_line_40_rect.xml
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/datasource/paging/LookPagingSource.kt
  data/src/main/java/com/example/data/model/response/look/ResponseLookListDto.kt
  data/src/main/java/com/example/data/remote/service/LookService.kt
  domain/src/main/java/com/example/domain/entity/LookListModel.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 상호 🍀

#365 [UI/#362] 친구 초대 다이얼로그 & Empty 뷰 수정
  app/src/main/res/layout/fragment_invite_friend_dialog.xml
  app/src/main/res/values/strings.xml
Labels: PULL REQUEST 🚀, UI 💐, 상호 🍀

#363 [FEAT/#350] Profile / 탈퇴 사유 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitDialog.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitReasonActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitReasonAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitTwoActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/EditNameActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/HighSchoolInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/group/GroupDialogFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/school/SearchDialogHighSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studenttype/SelectStudentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/studentid/StudentIdDialogFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/university/SearchDialogUniversityFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/yelloid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/PayReSubsNoticeDialog.kt
  app/src/main/res/drawable/ic_profile_quit_reason_check.xml
  app/src/main/res/drawable/ic_profile_quit_reason_uncheck.xml
  app/src/main/res/drawable/shape_black_fill_grayscales600_line_100_rect.xml
  app/src/main/res/drawable/shape_black_fill_white_line_8_rect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_grayscales700_circle.xml
  app/src/main/res/layout/activity_name_edit.xml
  app/src/main/res/layout/activity_profile_quit_reason.xml
  app/src/main/res/layout/activity_tutorial_end_point.xml
  app/src/main/res/layout/fragment_add_friend.xml
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/fragment_dialog_check_name.xml
  app/src/main/res/layout/fragment_dialog_department.xml
  app/src/main/res/layout/fragment_dialog_group.xml
  app/src/main/res/layout/fragment_dialog_highschool.xml
  app/src/main/res/layout/fragment_dialog_student_id.xml
  app/src/main/res/layout/fragment_dialog_university.xml
  app/src/main/res/layout/fragment_highschool.xml
  app/src/main/res/layout/fragment_select_student_type.xml
  app/src/main/res/layout/fragment_university.xml
  app/src/main/res/layout/fragment_yello_id.xml
  app/src/main/res/layout/item_profile_quit_reason.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/datasource/ProfileDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/ProfileDataSourceImpl.kt
  data/src/main/java/com/example/data/model/request/profile/RequestQuitReasonDto.kt
  data/src/main/java/com/example/data/remote/service/ProfileService.kt
  data/src/main/java/com/example/data/repository/OnboardingRepositoryImpl.kt
  data/src/main/java/com/example/data/repository/ProfileRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/ProfileQuitReasonModel.kt
  domain/src/main/java/com/example/domain/repository/OnboardingRepository.kt
  domain/src/main/java/com/example/domain/repository/ProfileRepository.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 민주 🌳

#367 [FEAT/#360] Yello / 투표하기 투표 전환 애니메이션 변경
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteActivity.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/frame/NoteFrameAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/frame/NoteFrameFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteFragment.kt
  app/src/main/java/com/el/yello/util/binding/BindingAdapter.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_vote.xml
  app/src/main/res/layout/fragment_note.xml
  app/src/main/res/layout/fragment_note_frame.xml
  app/src/main/res/navigation/navigation_onboarding.xml
Labels: FEAT ✨, PULL REQUEST 🚀, 채연 🐸

#371 [FIX/#370] Notice / 구독 연장 여부 서버 통신 재호출 수정
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayReSubsNoticeDialog.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#369 [UI/#368] MyYello / 스토리 공유 버튼 강조
  app/src/main/java/com/el/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/point/PointFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/res/drawable-hdpi/ic_instagram.png
  app/src/main/res/drawable-mdpi/ic_instagram.png
  app/src/main/res/drawable-xhdpi/ic_instagram.png
  app/src/main/res/drawable-xxhdpi/ic_instagram.png
  app/src/main/res/drawable-xxxhdpi/ic_instagram.png
  app/src/main/res/drawable/shape_white59_fill_100_rect.xml
  app/src/main/res/layout/activity_my_yello_read.xml
  app/src/main/res/values/strings.xml
Labels: PULL REQUEST 🚀, UI 💐, 채연 🐸

#373 [FEAT#364] MyYello / 내 쪽지 뷰 변경사항 반영
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/dialog/notice/NoticeDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/res/drawable/ic_my_yello_notice.xml
  app/src/main/res/drawable/shape_grayscales900_fill_18_rect.xml
  app/src/main/res/layout/fragment_my_yello.xml
  app/src/main/res/layout/fragment_yello_start.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/datasource/NoticeDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/NoticeDataSourceImpl.kt
  data/src/main/java/com/example/data/model/response/notice/ResponseGetNotice.kt
  data/src/main/java/com/example/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/notice/Banner.kt
  domain/src/main/java/com/example/domain/repository/NoticeRepository.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 채연 🐸

#375 [FEAT/#372] Profile / 프로필 배너 설정
  app/src/main/java/com/el/yello/presentation/main/profile/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileUserInfoViewHolder.kt
  app/src/main/res/layout/item_profile_user_info.xml
  data/src/main/java/com/example/data/datasource/NoticeDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/NoticeDataSourceImpl.kt
  data/src/main/java/com/example/data/model/response/notice/ResponseGetNotice.kt
  data/src/main/java/com/example/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/notice/ProfileBanner.kt
  domain/src/main/java/com/example/domain/repository/NoticeRepository.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 상호 🍀

#377 [UI/#376] OnBoarding / 추천인 코드 버튼 간격 변경
  app/src/main/res/layout/fragment_code.xml
Labels: PULL REQUEST 🚀, UI 💐, 민주 🌳

#378 [FEAT/#374] Event / 점심시간 이벤트 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/di/DataSourceModule.kt
  app/src/main/java/com/el/yello/di/RepositoryModule.kt
  app/src/main/java/com/el/yello/di/ServiceModule.kt
  app/src/main/java/com/el/yello/presentation/event/EventActivity.kt
  app/src/main/java/com/el/yello/presentation/event/EventViewModel.kt
  app/src/main/java/com/el/yello/presentation/event/RewardAdapter.kt
  app/src/main/java/com/el/yello/presentation/event/reward/RewardDialog.kt
  app/src/main/java/com/el/yello/presentation/event/reward/RewardViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/MainViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/ParcelableEvent.kt
  app/src/main/java/com/el/yello/presentation/main/ParcelableReward.kt
  app/src/main/java/com/el/yello/presentation/main/dialog/notice/NoticeDialog.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/res/drawable/img_event_key.xml
  app/src/main/res/drawable/img_event_point.xml
  app/src/main/res/drawable/shape_gradient_event_bg.xml
  app/src/main/res/drawable/shape_grayscales900_fill_10_rect.xml
  app/src/main/res/drawable/shape_grayscales900_fill_22_rect.xml
  app/src/main/res/layout/activity_event.xml
  app/src/main/res/layout/fragment_reward_dialog.xml
  app/src/main/res/layout/item_event_reward.xml
  app/src/main/res/raw/lottie_event_default.json
  app/src/main/res/raw/lottie_event_open.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  core-ui/src/main/java/com/example/ui/diff/DiffCallback.kt
  core-ui/src/main/java/com/example/ui/intent/ExtraExt.kt
  data/src/main/java/com/example/data/datasource/EventDataSource.kt
  data/src/main/java/com/example/data/datasource/NoticeDataSource.kt
  data/src/main/java/com/example/data/datasource/YelloDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/EventDataSourceImpl.kt
  data/src/main/java/com/example/data/datasource/remote/NoticeDataSourceImpl.kt
  data/src/main/java/com/example/data/datasource/remote/YelloDataSourceImpl.kt
  data/src/main/java/com/example/data/model/request/event/RequestPostEventStateDto.kt
  data/src/main/java/com/example/data/model/response/event/ResponseGetEventDto.kt
  data/src/main/java/com/example/data/model/response/event/ResponsePostEventDto.kt
  data/src/main/java/com/example/data/model/response/notice/ResponseGetNotice.kt
  data/src/main/java/com/example/data/model/response/vote/ResponseVoteCount.kt
  data/src/main/java/com/example/data/remote/service/EventService.kt
  data/src/main/java/com/example/data/remote/service/NoticeService.kt
  data/src/main/java/com/example/data/remote/service/YelloService.kt
  data/src/main/java/com/example/data/repository/EventRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/event/Event.kt
  domain/src/main/java/com/example/domain/entity/event/EventResult.kt
  domain/src/main/java/com/example/domain/repository/EventRepository.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 채연 🐸

#380 [FIX/#379] Event / SVG 이미지 로드 이슈 해결
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/event/RewardAdapter.kt
  app/src/main/java/com/el/yello/presentation/event/reward/RewardDialog.kt
  app/src/main/java/com/el/yello/presentation/main/dialog/notice/NoticeDialog.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileUserInfoViewHolder.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendViewHolder.kt
  app/src/main/java/com/el/yello/util/Image/ImageViewExt.kt
  app/src/main/java/com/el/yello/util/Utils.kt
  app/src/main/res/layout/fragment_reward_dialog.xml
  app/src/main/res/layout/item_event_reward.xml
  gradle/libs.versions.toml
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#382 [FIX/#379] Main / 공지 팝업 중복 발생 이슈 해결
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#383 [CHORE/#381] version name 2.0
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: CHORE 🎀, 상호 🍀

#386 [CHORE/#385] Debug Builder develop 연동 비활성화
  .github/workflows/debug_builder.yml
  .github/workflows/pr_checker.yml
Labels: CHORE 🎀, PULL REQUEST 🚀, 채연 🐸

#389 [FIX/#384] Timeline, Profile / 3차 스프린트 QA 반영
  app/src/main/java/com/el/yello/presentation/main/profile/detail/ProfileDetailActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileUserInfoViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/SchoolProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/SchoolProfileModViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/UnivModSearchBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/UnivProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/UnivProfileModViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoViewModel.kt
  app/src/main/java/com/el/yello/util/Utils.kt
  app/src/main/res/layout/activity_profile_school_mod.xml
  app/src/main/res/layout/activity_profile_univ_mod.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#391 [FIX/#388] Yello, MyYello / 3차 스프린트 1차 QA 피드백 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/event/EventActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/start/YelloStartFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/frame/NoteFrameFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/note/NoteFragment.kt
  app/src/main/java/com/el/yello/util/binding/BindingAdapter.kt
  app/src/main/res/layout/activity_my_yello_read.xml
  app/src/main/res/layout/fragment_note_frame.xml
  app/src/main/res/values/strings.xml
  core-ui/src/main/java/com/example/ui/context/ContextExt.kt
  core-ui/src/main/java/com/example/ui/restart/RestartApp.kt
  core-ui/src/main/java/com/example/ui/view/ViewExt.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#392 [FIX/#387] OnBoarding, Splash, Withdrawl / 3차 스프린트 1차 QA 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/onboarding/activity/EditNameActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendViewHolder.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/checkName/CheckNameDialog.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/HighSchoolInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/school/HighSchoolAdapter.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/school/SearchDialogHighSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/studenttype/SelectStudentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/UniversityInfoFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/university/SearchDialogUniversityFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/yelloid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_code.xml
  app/src/main/res/layout/item_profile_quit_reason.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  domain/src/main/java/com/example/domain/enum/Grade.kt
  domain/src/main/java/com/example/domain/enum/StudentType.kt
  gradle/libs.versions.toml
Labels: FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#393 [REFACTOR/#254] 토스트 옐로 스낵바 반영
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/el/yello/presentation/event/EventActivity.kt
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/MainViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/ParcelableEvent.kt
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/detail/ProfileDetailActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendDeleteBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileManageActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/manage/ProfileQuitDialog.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/SchoolModSearchBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/SchoolProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/UnivModSearchBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/UnivProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteActivity.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/frame/NoteFrameFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/EditNameActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/activity/OnBoardingActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/checkName/CheckNameDialog.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/highschoolinfo/school/SearchDialogHighSchoolFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/department/SearchDialogDepartmentFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/universityinfo/university/SearchDialogUniversityFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/yelloid/YelIoIdFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/search/SearchActivity.kt
  app/src/main/java/com/el/yello/presentation/splash/SplashActivity.kt
  app/src/main/java/com/el/yello/util/context/ContextExt.kt
  app/src/main/res/layout/activity_event.xml
  app/src/main/res/values/strings.xml
  core-ui/src/main/java/com/example/ui/restart/RestartApp.kt
  data/src/main/java/com/example/data/model/response/event/ResponseGetEventDto.kt
  data/src/main/java/com/example/data/repository/EventRepositoryImpl.kt
  domain/src/main/java/com/example/domain/entity/event/Event.kt
Labels: PULL REQUEST 🚀, REFACTOR ♻️, 채연 🐸

#395 [FIX/#394] 서버통신 state 값 중복 collect 현상 해결
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/MainViewModel.kt
  app/src/main/java/com/el/yello/presentation/pay/PayReSubsNoticeDialog.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#396 [FEAT/#390] 상점,투표 뷰 보상형 광고 구현 & 검증 / 내쪽지뷰 랜덤 전면 광고 구현
  .github/workflows/pr_checker.yml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/MyApp.kt
  app/src/main/java/com/el/yello/presentation/event/reward/RewardDialog.kt
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/point/PointFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/vote/VoteViewModel.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayViewModel.kt
  app/src/main/java/com/el/yello/presentation/pay/dialog/PayInAppDialog.kt
  app/src/main/java/com/el/yello/presentation/pay/dialog/PayPointDialog.kt
  app/src/main/java/com/el/yello/presentation/pay/dialog/PayReSubsNoticeDialog.kt
  app/src/main/java/com/el/yello/presentation/pay/dialog/PaySubsDialog.kt
  app/src/main/res/drawable/ic_coin.xml
  app/src/main/res/drawable/ic_key_1.xml
  app/src/main/res/drawable/shape_black_fill_grayscales800_line_10_rect.xml
  app/src/main/res/layout/activity_pay.xml
  app/src/main/res/layout/fragment_pay_point_dialog.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build-logic/convention/src/main/kotlin/plugins/AndroidApplicationPlugin.kt
  data/src/main/java/com/example/data/datasource/EventDataSource.kt
  data/src/main/java/com/example/data/datasource/remote/EventDataSourceImpl.kt
  data/src/main/java/com/example/data/model/request/event/RequestRewardAdDto.kt
  data/src/main/java/com/example/data/model/response/event/ResponseRewardAdDto.kt
  data/src/main/java/com/example/data/model/response/event/ResponseRewardAdPossibleDto.kt
  data/src/main/java/com/example/data/model/response/profile/ResponseProfileFriendsListDto.kt
  data/src/main/java/com/example/data/model/response/profile/ResponseProfileUserDto.kt
  data/src/main/java/com/example/data/model/response/vote/ResponseGetVoteAvailableDto.kt
  data/src/main/java/com/example/data/remote/service/EventService.kt
  data/src/main/java/com/example/data/repository/EventRepositoryImpl.kt
  data/src/main/java/com/example/data/util/StringExt.kt
  domain/src/main/java/com/example/domain/entity/ProfileUserModel.kt
  domain/src/main/java/com/example/domain/entity/event/RewardAdModel.kt
  domain/src/main/java/com/example/domain/entity/event/RewardAdPossibleModel.kt
  domain/src/main/java/com/example/domain/entity/event/RewardAdRequestModel.kt
  domain/src/main/java/com/example/domain/repository/EventRepository.kt
  gradle/libs.versions.toml
Labels: FEAT ✨, PULL REQUEST 🚀, 상호 🍀

#400 [FIX/#397] OnBoarding / 3차 스프린트 2차 QA 반영
  app/src/main/java/com/el/yello/presentation/onboarding/activity/EditNameActivity.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/yelloid/YelIoIdFragment.kt
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#401 [FIX/#399] Timeline, Recommend / 3차 스프린트 2차 QA 피드백 반영
  app/src/main/java/com/el/yello/presentation/main/look/LookFragment.kt
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#402 [FIX/#398] Yello, MyYello / 3차 스프린트 2차 QA 피드백 반영
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/read/MyYelloReadActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/detail/ProfileDetailActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/SchoolProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/mod/UnivProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/yello/point/PointFragment.kt
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸

#405 [REFACTOR/#355] Profile / 폴더링 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/detail/ProfileDetailActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendDeleteBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendItemBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileUserInfoViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/schoolmod/SchoolModClassroomBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/schoolmod/SchoolModGradeBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/schoolmod/SchoolModSearchBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/schoolmod/SchoolProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/schoolmod/SchoolProfileModViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/univmod/UnivModSearchBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/univmod/UnivModSelectBottomSheet.kt
  app/src/main/java/com/el/yello/presentation/main/profile/univmod/UnivProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/univmod/UnivProfileModViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/timeline/TimelineFragment.kt
  app/src/main/java/com/el/yello/presentation/main/timeline/TimelinePageAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/timeline/TimelineViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/timeline/TimelineViewModel.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitDialog.kt
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitOneActivity.kt
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitReasonActivity.kt
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitReasonAdapter.kt
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitTwoActivity.kt
  app/src/main/java/com/el/yello/presentation/setting/SettingActivity.kt
  app/src/main/java/com/el/yello/presentation/setting/SettingViewModel.kt
  app/src/main/res/layout/activity_profile_quit_reason.xml
  app/src/main/res/layout/activity_profile_school_mod.xml
  app/src/main/res/layout/activity_profile_univ_mod.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_profile_delete_bottom_sheet.xml
  app/src/main/res/layout/fragment_profile_item_bottom_sheet.xml
  app/src/main/res/layout/fragment_timeline.xml
  app/src/main/res/layout/item_profile_user_info.xml
  app/src/main/res/layout/item_timeline.xml
  core-ui/src/main/java/com/example/ui/util/Utils.kt
Labels: PULL REQUEST 🚀, REFACTOR ♻️, 상호 🍀

#410 [FIX/#409] restart 유틸 수정
  app/src/main/java/com/el/yello/presentation/setting/ProfileQuitDialog.kt
Labels: HOTFIX 🚑️, PULL REQUEST 🚀, 상호 🍀

#411 [DOCS] 리드미 tech stack 업데이트
  README.md
Labels: PULL REQUEST 🚀, 상호 🍀

#412 [FIX/#408] Pay / 상점 배너 아이템 1개로 통일
  app/src/main/java/com/el/yello/presentation/pay/banner/BannerItem.kt
  app/src/main/java/com/el/yello/presentation/pay/banner/PayBannerAdapter.kt
  app/src/main/java/com/el/yello/presentation/pay/banner/PayBannerViewHolder.kt
  app/src/main/res/drawable/ic_pay_foot_second.xml
  app/src/main/res/drawable/ic_pay_head_first.xml
  app/src/main/res/drawable/ic_pay_head_fourth.xml
  app/src/main/res/drawable/ic_pay_head_second.xml
  app/src/main/res/drawable/ic_pay_head_third.xml
  app/src/main/res/drawable/ic_pay_under_first.xml
  app/src/main/res/drawable/img_pay_banner_first.xml
  app/src/main/res/drawable/img_pay_banner_fourth.xml
  app/src/main/res/drawable/img_pay_banner_second.xml
  app/src/main/res/drawable/img_pay_banner_third.xml
  app/src/main/res/layout/item_pay_banner.xml
  app/src/main/res/layout/item_pay_first.xml
  app/src/main/res/layout/item_pay_fourth.xml
  app/src/main/res/layout/item_pay_second.xml
  app/src/main/res/layout/item_pay_third.xml
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀

#415 [FIX/#413] OnBoarding / 추천친구 기본프사 옐로 이미지 적용
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/addfriend/AddFriendViewHolder.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 민주 🌳

#418 [FIX/#417] 구독 정보 조회 실패 시 발생하는 토스트 제거
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/MainViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/yello/YelloViewModel.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 채연 🐸
