Repository team-yello/YELLO-Android, pull requests merged in 2024-03, with the labels that each got.

#421 [HOTFIX/#420] EditNameActivity 이슈 대응
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: HOTFIX 🚑️, 상호 🍀

#422 [FEAT/#419] 푸시 알림(FCM) 추가 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/el/yello/config/YelloMessagingService.kt
  app/src/main/java/com/el/yello/presentation/auth/SignInActivity.kt
  app/src/main/java/com/el/yello/presentation/auth/SocialSyncActivity.kt
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/timeline/TimelineFragment.kt
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 민주 🌳

#426 [FEAT/#425] Notice / 공지 오늘 하루 보지 않기 기능 구현
  README.md
  app/src/main/res/layout/fragment_notice_dialog.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/example/data/local/YelloDataStoreImpl.kt
  data/src/main/java/com/example/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/com/example/domain/YelloDataStore.kt
Labels: FEAT ✨, PULL REQUEST 🚀, 채연 🐸

#428 [HOTFIX/#427] Recommend / 카톡 친구 불러오기 실패 이슈 해결
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoFragment.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/kakao/RecommendKakaoViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/recommend/school/RecommendSchoolViewModel.kt
  app/src/main/java/com/el/yello/presentation/search/SearchViewModel.kt
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: HOTFIX 🚑️, PULL REQUEST 🚀, 상호 🍀

#430 [ADD/#429] 3차 스프린트 Amplitude 추가
  app/src/main/java/com/el/yello/presentation/event/EventActivity.kt
  app/src/main/java/com/el/yello/presentation/event/reward/RewardDialog.kt
  app/src/main/java/com/el/yello/presentation/main/dialog/notice/NoticeDialog.kt
  app/src/main/java/com/el/yello/presentation/main/myyello/MyYelloFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/detail/ProfileDetailActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFragment.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileFriendAdapter.kt
  app/src/main/java/com/el/yello/presentation/main/profile/info/ProfileUserInfoViewHolder.kt
  app/src/main/java/com/el/yello/presentation/main/profile/schoolmod/SchoolProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/profile/schoolmod/SchoolProfileModViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/profile/univmod/UnivProfileModActivity.kt
  app/src/main/java/com/el/yello/presentation/main/timeline/TimelineFragment.kt
  app/src/main/java/com/el/yello/presentation/main/yello/point/PointFragment.kt
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/dialog/PayReSubsNoticeDialog.kt
Labels: ADD ➕, PULL REQUEST 🚀, 민주 🌳

#432 [FIX/#431] Timeline / 내쪽지 필터 Empty시 투표 뷰로 이동 구현
  app/src/main/java/com/el/yello/presentation/main/MainActivity.kt
  app/src/main/java/com/el/yello/presentation/main/dialog/notice/NoticeDialog.kt
  app/src/main/java/com/el/yello/presentation/main/dialog/notice/NoticeViewModel.kt
  app/src/main/java/com/el/yello/presentation/main/timeline/TimelineFragment.kt
  app/src/main/res/layout/fragment_timeline.xml
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: FIX 🔨, PULL REQUEST 🚀, 상호 🍀
