Repository team-yello/YELLO-Android, pull requests merged in 2024-07, with the labels that each got.

#450 [CHORE/#449] PR CHECKER 수정
  .github/workflows/pr_checker.yml
Labels: CHORE 🎀, 강민 🦖

#448 [CHORE/#447] target sdk 34
  app/src/main/java/com/el/yello/util/custom/YelloStartShadowView.kt
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/Constants.kt
  build-logic/convention/src/main/kotlin/plugins/AndroidApplicationPlugin.kt
  build-logic/convention/src/main/kotlin/plugins/AndroidLibraryPlugin.kt
  domain/build.gradle.kts
  gradle/libs.versions.toml
Labels: CHORE 🎀, 강민 🦖

#452 [MOD/#451] 회원가입 토스트 에러 코드 메시지 추가
  app/src/main/java/com/el/yello/presentation/onboarding/fragment/code/CodeFragment.kt
  build-logic/convention/src/main/kotlin/Constants.kt
  core-ui/src/main/java/com/example/ui/state/UiState.kt
Labels: MOD ✅, PULL REQUEST 🚀, 민주 🌳

#454 [CHORE/#453] Compose Setting
  app/build.gradle.kts
  app/src/main/java/com/el/yello/util/extension/ImageViewExt.kt
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/plugins/AndroidApplicationComposePlugin.kt
  gradle/libs.versions.toml
Labels: CHORE 🎀, 강민 🦖

#456 [CHORE/#455] Compose Design 설정
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/ext/ConfigureAndroidCompose.kt
  build-logic/convention/src/main/kotlin/plugins/AndroidApplicationComposePlugin.kt
  build-logic/convention/src/main/kotlin/plugins/AndroidLibraryComposePlugin.kt
  core-ui/build.gradle.kts
  core-ui/src/main/java/com/example/ui/compose/theme/Color.kt
  core-ui/src/main/java/com/example/ui/compose/theme/DesignTypo.kt
  core-ui/src/main/java/com/example/ui/compose/theme/Theme.kt
  core-ui/src/main/res/font/font_pretendard_bold.xml
  core-ui/src/main/res/font/font_pretendard_medium.xml
  core-ui/src/main/res/font/font_pretendard_regular.xml
  core-ui/src/main/res/font/font_pretendard_semibold.xml
  core-ui/src/main/res/font/pretendard_bold.otf
  core-ui/src/main/res/font/pretendard_medium.otf
  core-ui/src/main/res/font/pretendard_regular.otf
  core-ui/src/main/res/font/pretendard_semibold.otf
  core-ui/src/main/res/font/unbounded_black.ttf
  core-ui/src/main/res/font/unbounded_bold.ttf
  core-ui/src/main/res/font/unbounded_extrabold.ttf
  core-ui/src/main/res/font/unbounded_extralight.ttf
  core-ui/src/main/res/font/unbounded_light.ttf
  core-ui/src/main/res/font/unbounded_medium.ttf
  core-ui/src/main/res/font/unbounded_regular.ttf
  core-ui/src/main/res/font/unbounded_semibold.ttf
Labels: CHORE 🎀

#459 [FIX/#458] admob 보상형 광고 서버 null 처리방법 변경
  app/src/main/java/com/el/yello/presentation/pay/PayActivity.kt
  app/src/main/java/com/el/yello/presentation/pay/PayViewModel.kt
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/kotlin/Constants.kt
Labels: FIX 🔨, 상호 🍀
